version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - /dev/input:/dev/input  # Monta o dispositivo de entrada do teclado no contêiner
    - ./src:/app/src
    - ./src/backups:/app/backups
    - ./src/logs:/app/logs
    networks:
      - zap_network
    ports:
      - "8050:8050/udp"  # Mapeamento da porta UDP
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true  # Concede privilégios adicionais ao contêiner

networks:
  zap_network:
    external: true
    name: host
